resource_labels = { "provider" : "jx" }
jx_git_url = "https://github.com/lfs268-eeganlf/jx3-gke-gsm"
gcp_project = "ci-cd-349400"
cluster_name = "lfs268-lab"
cluster_location  = "us-central1-a"
gsm = true
force_destroy = true
delete_protect = false
jx_bot_username = "eeganlf"
jx_bot_token = ""
